version: 2

sources:
  - name: mercurymart_raw
    database: ANALYTICS
    schema: RAW

    tables:
      - name: RAW_CUSTOMERS
      - name: RAW_ORDERS
      - name: RAW_ORDER_ITEMS
      - name: RAW_PAYMENTS
      - name: RAW_PRODUCTS
      - name: RAW_REFUNDS
