version: 2

models:

  - name: dim_mercurymart__customers
    description: Customer dimension with lifetime metrics and loyalty tier
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: number
        tests:
          - not_null
          - unique

      - name: first_name
        data_type: varchar
      - name: last_name
        data_type: varchar
      - name: email
        data_type: varchar
      - name: country
        data_type: varchar
      - name: segment
        data_type: varchar
      - name: first_order_date
        data_type: date
      - name: total_orders
        data_type: number
      - name: loyalty_tier
        data_type: varchar


  - name: fct_mercurymart__orders_daily
    description: Daily order fact table
    latest_version: 2
    config:
      contract:
        enforced: true        # 🔥 THIS WAS MISSING
    versions:

      - v: 1
        columns:
          - name: order_id
            data_type: number
          - name: order_date
            data_type: date
          - name: customer_id
            data_type: number
          - name: gross_amount
            data_type: number(38,2)
          - name: net_amount
            data_type: number(38,2)
          - name: payment_status
            data_type: varchar

      - v: 2
        description: Adds order day of week for better time analysis
        columns:
          - name: order_id
            data_type: number
          - name: order_date
            data_type: date
          - name: customer_id
            data_type: number
          - name: gross_amount
            data_type: number(38,2)
          - name: payment_amount
            data_type: number(38,2)
          - name: refund_amount
            data_type: number(38,2)
          - name: net_amount
            data_type: number(38,2)
          - name: payment_status
            data_type: varchar
          - name: order_day_of_week
            data_type: varchar

